//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the vesc_driver package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __vesc_driver__VESCCONFIG_H__
#define __vesc_driver__VESCCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace vesc_driver
{
  class VESCConfigStatics;
  
  class VESCConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(VESCConfig &config, const VESCConfig &max, const VESCConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const VESCConfig &config1, const VESCConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, VESCConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const VESCConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, VESCConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const VESCConfig &config) const = 0;
      virtual void getValue(const VESCConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T VESCConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (VESCConfig::* field);

      virtual void clamp(VESCConfig &config, const VESCConfig &max, const VESCConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const VESCConfig &config1, const VESCConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, VESCConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const VESCConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, VESCConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const VESCConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const VESCConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, VESCConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, VESCConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<VESCConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(VESCConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("pwm_mode"==(*_i)->name){pwm_mode = boost::any_cast<int>(val);}
        if("comm_mode"==(*_i)->name){comm_mode = boost::any_cast<int>(val);}
        if("motor_type"==(*_i)->name){motor_type = boost::any_cast<int>(val);}
        if("sensor_mode"==(*_i)->name){sensor_mode = boost::any_cast<int>(val);}
        if("l_current_max"==(*_i)->name){l_current_max = boost::any_cast<double>(val);}
        if("l_current_min"==(*_i)->name){l_current_min = boost::any_cast<double>(val);}
        if("l_in_current_max"==(*_i)->name){l_in_current_max = boost::any_cast<double>(val);}
        if("l_in_current_min"==(*_i)->name){l_in_current_min = boost::any_cast<double>(val);}
        if("l_abs_current_max"==(*_i)->name){l_abs_current_max = boost::any_cast<double>(val);}
        if("l_min_erpm"==(*_i)->name){l_min_erpm = boost::any_cast<double>(val);}
        if("l_max_erpm"==(*_i)->name){l_max_erpm = boost::any_cast<double>(val);}
        if("l_max_erpm_fbrake"==(*_i)->name){l_max_erpm_fbrake = boost::any_cast<double>(val);}
        if("l_max_erpm_fbrake_cc"==(*_i)->name){l_max_erpm_fbrake_cc = boost::any_cast<double>(val);}
        if("l_min_vin"==(*_i)->name){l_min_vin = boost::any_cast<double>(val);}
        if("l_max_vin"==(*_i)->name){l_max_vin = boost::any_cast<double>(val);}
        if("l_slow_abs_current"==(*_i)->name){l_slow_abs_current = boost::any_cast<bool>(val);}
        if("l_rpm_lim_neg_torque"==(*_i)->name){l_rpm_lim_neg_torque = boost::any_cast<bool>(val);}
        if("l_temp_fet_start"==(*_i)->name){l_temp_fet_start = boost::any_cast<double>(val);}
        if("l_temp_fet_end"==(*_i)->name){l_temp_fet_end = boost::any_cast<double>(val);}
        if("l_temp_motor_start"==(*_i)->name){l_temp_motor_start = boost::any_cast<double>(val);}
        if("l_temp_motor_end"==(*_i)->name){l_temp_motor_end = boost::any_cast<double>(val);}
        if("l_min_duty"==(*_i)->name){l_min_duty = boost::any_cast<double>(val);}
        if("l_max_duty"==(*_i)->name){l_max_duty = boost::any_cast<double>(val);}
        if("sl_min_erpm"==(*_i)->name){sl_min_erpm = boost::any_cast<double>(val);}
        if("sl_min_erpm_cycle_int_limit"==(*_i)->name){sl_min_erpm_cycle_int_limit = boost::any_cast<double>(val);}
        if("sl_max_fullbreak_current_dir_change"==(*_i)->name){sl_max_fullbreak_current_dir_change = boost::any_cast<double>(val);}
        if("sl_cycle_int_limit"==(*_i)->name){sl_cycle_int_limit = boost::any_cast<double>(val);}
        if("sl_phase_advance_at_br"==(*_i)->name){sl_phase_advance_at_br = boost::any_cast<double>(val);}
        if("sl_cycle_int_rpm_br"==(*_i)->name){sl_cycle_int_rpm_br = boost::any_cast<double>(val);}
        if("sl_bemf_coupling_k"==(*_i)->name){sl_bemf_coupling_k = boost::any_cast<double>(val);}
        if("hall_table_0"==(*_i)->name){hall_table_0 = boost::any_cast<int>(val);}
        if("hall_table_1"==(*_i)->name){hall_table_1 = boost::any_cast<int>(val);}
        if("hall_table_2"==(*_i)->name){hall_table_2 = boost::any_cast<int>(val);}
        if("hall_table_3"==(*_i)->name){hall_table_3 = boost::any_cast<int>(val);}
        if("hall_table_4"==(*_i)->name){hall_table_4 = boost::any_cast<int>(val);}
        if("hall_table_5"==(*_i)->name){hall_table_5 = boost::any_cast<int>(val);}
        if("hall_table_6"==(*_i)->name){hall_table_6 = boost::any_cast<int>(val);}
        if("hall_table_7"==(*_i)->name){hall_table_7 = boost::any_cast<int>(val);}
        if("hall_sl_erpm"==(*_i)->name){hall_sl_erpm = boost::any_cast<double>(val);}
        if("s_pid_kp"==(*_i)->name){s_pid_kp = boost::any_cast<double>(val);}
        if("s_pid_ki"==(*_i)->name){s_pid_ki = boost::any_cast<double>(val);}
        if("s_pid_kd"==(*_i)->name){s_pid_kd = boost::any_cast<double>(val);}
        if("s_pid_min_rpm"==(*_i)->name){s_pid_min_rpm = boost::any_cast<double>(val);}
        if("p_pid_kp"==(*_i)->name){p_pid_kp = boost::any_cast<double>(val);}
        if("p_pid_ki"==(*_i)->name){p_pid_ki = boost::any_cast<double>(val);}
        if("p_pid_kd"==(*_i)->name){p_pid_kd = boost::any_cast<double>(val);}
        if("cc_startup_boost_duty"==(*_i)->name){cc_startup_boost_duty = boost::any_cast<double>(val);}
        if("cc_min_current"==(*_i)->name){cc_min_current = boost::any_cast<double>(val);}
        if("cc_gain"==(*_i)->name){cc_gain = boost::any_cast<double>(val);}
        if("cc_ramp_step_max"==(*_i)->name){cc_ramp_step_max = boost::any_cast<double>(val);}
        if("m_fault_stop_time_ms"==(*_i)->name){m_fault_stop_time_ms = boost::any_cast<int>(val);}
      }
    }

    int pwm_mode;
int comm_mode;
int motor_type;
int sensor_mode;
double l_current_max;
double l_current_min;
double l_in_current_max;
double l_in_current_min;
double l_abs_current_max;
double l_min_erpm;
double l_max_erpm;
double l_max_erpm_fbrake;
double l_max_erpm_fbrake_cc;
double l_min_vin;
double l_max_vin;
bool l_slow_abs_current;
bool l_rpm_lim_neg_torque;
double l_temp_fet_start;
double l_temp_fet_end;
double l_temp_motor_start;
double l_temp_motor_end;
double l_min_duty;
double l_max_duty;
double sl_min_erpm;
double sl_min_erpm_cycle_int_limit;
double sl_max_fullbreak_current_dir_change;
double sl_cycle_int_limit;
double sl_phase_advance_at_br;
double sl_cycle_int_rpm_br;
double sl_bemf_coupling_k;
int hall_table_0;
int hall_table_1;
int hall_table_2;
int hall_table_3;
int hall_table_4;
int hall_table_5;
int hall_table_6;
int hall_table_7;
double hall_sl_erpm;
double s_pid_kp;
double s_pid_ki;
double s_pid_kd;
double s_pid_min_rpm;
double p_pid_kp;
double p_pid_ki;
double p_pid_kd;
double cc_startup_boost_duty;
double cc_min_current;
double cc_gain;
double cc_ramp_step_max;
int m_fault_stop_time_ms;

    bool state;
    std::string name;

    
}groups;



//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int pwm_mode;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int comm_mode;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int motor_type;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int sensor_mode;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_current_max;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_current_min;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_in_current_max;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_in_current_min;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_abs_current_max;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_min_erpm;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_max_erpm;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_max_erpm_fbrake;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_max_erpm_fbrake_cc;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_min_vin;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_max_vin;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool l_slow_abs_current;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool l_rpm_lim_neg_torque;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_temp_fet_start;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_temp_fet_end;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_temp_motor_start;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_temp_motor_end;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_min_duty;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double l_max_duty;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sl_min_erpm;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sl_min_erpm_cycle_int_limit;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sl_max_fullbreak_current_dir_change;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sl_cycle_int_limit;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sl_phase_advance_at_br;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sl_cycle_int_rpm_br;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sl_bemf_coupling_k;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int hall_table_0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int hall_table_1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int hall_table_2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int hall_table_3;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int hall_table_4;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int hall_table_5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int hall_table_6;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int hall_table_7;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double hall_sl_erpm;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s_pid_kp;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s_pid_ki;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s_pid_kd;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s_pid_min_rpm;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p_pid_kp;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p_pid_ki;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p_pid_kd;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double cc_startup_boost_duty;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double cc_min_current;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double cc_gain;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double cc_ramp_step_max;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int m_fault_stop_time_ms;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("VESCConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const VESCConfig &__max__ = __getMax__();
      const VESCConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const VESCConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const VESCConfig &__getDefault__();
    static const VESCConfig &__getMax__();
    static const VESCConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const VESCConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void VESCConfig::ParamDescription<std::string>::clamp(VESCConfig &config, const VESCConfig &max, const VESCConfig &min) const
  {
    return;
  }

  class VESCConfigStatics
  {
    friend class VESCConfig;
    
    VESCConfigStatics()
    {
VESCConfig::GroupDescription<VESCConfig::DEFAULT, VESCConfig> Default("Default", "", 0, 0, true, &VESCConfig::groups);
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pwm_mode = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pwm_mode = 2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pwm_mode = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("pwm_mode", "int", 0, "PWM Mode", "{'enum_description': 'PWM Mode', 'enum': [{'srcline': 8, 'description': 'This mode is not recommended', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Nonsynchronous'}, {'srcline': 9, 'description': 'Recommended and most tested mode', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Synchronous'}, {'srcline': 10, 'description': 'Some glitches occasionally, can kill MOSFETs', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Bipolar'}]}", &VESCConfig::pwm_mode)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("pwm_mode", "int", 0, "PWM Mode", "{'enum_description': 'PWM Mode', 'enum': [{'srcline': 8, 'description': 'This mode is not recommended', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Nonsynchronous'}, {'srcline': 9, 'description': 'Recommended and most tested mode', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Synchronous'}, {'srcline': 10, 'description': 'Some glitches occasionally, can kill MOSFETs', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Bipolar'}]}", &VESCConfig::pwm_mode)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.comm_mode = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.comm_mode = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.comm_mode = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("comm_mode", "int", 0, "Commutation Mode", "{'enum_description': 'Commutation Mode', 'enum': [{'srcline': 13, 'description': 'Integrate', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Integrate'}, {'srcline': 14, 'description': 'Delay', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Delay'}]}", &VESCConfig::comm_mode)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("comm_mode", "int", 0, "Commutation Mode", "{'enum_description': 'Commutation Mode', 'enum': [{'srcline': 13, 'description': 'Integrate', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Integrate'}, {'srcline': 14, 'description': 'Delay', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Delay'}]}", &VESCConfig::comm_mode)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.motor_type = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.motor_type = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.motor_type = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("motor_type", "int", 0, "Motor Type", "{'enum_description': 'Motor Type', 'enum': [{'srcline': 17, 'description': 'Brushless Direct Current', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'BLDC'}, {'srcline': 18, 'description': 'Brushed Direct Current', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'DC'}]}", &VESCConfig::motor_type)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("motor_type", "int", 0, "Motor Type", "{'enum_description': 'Motor Type', 'enum': [{'srcline': 17, 'description': 'Brushless Direct Current', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'BLDC'}, {'srcline': 18, 'description': 'Brushed Direct Current', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'DC'}]}", &VESCConfig::motor_type)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sensor_mode = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sensor_mode = 2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sensor_mode = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("sensor_mode", "int", 0, "Sensor Mode", "{'enum_description': 'Sensor Mode', 'enum': [{'srcline': 21, 'description': 'Sensorless Mode', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Sensorless'}, {'srcline': 22, 'description': 'Sensored Mode', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Sensored'}, {'srcline': 23, 'description': 'Hybrid Sensored/Sensorless Mode', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Hybrid'}]}", &VESCConfig::sensor_mode)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("sensor_mode", "int", 0, "Sensor Mode", "{'enum_description': 'Sensor Mode', 'enum': [{'srcline': 21, 'description': 'Sensorless Mode', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Sensorless'}, {'srcline': 22, 'description': 'Sensored Mode', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Sensored'}, {'srcline': 23, 'description': 'Hybrid Sensored/Sensorless Mode', 'srcfile': '/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Hybrid'}]}", &VESCConfig::sensor_mode)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_current_max = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_current_max = 200.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_current_max = 60.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_current_max", "double", 0, "Maximum motor current", "", &VESCConfig::l_current_max)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_current_max", "double", 0, "Maximum motor current", "", &VESCConfig::l_current_max)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_current_min = -200.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_current_min = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_current_min = -60.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_current_min", "double", 0, "Minimum motor current (regen)", "", &VESCConfig::l_current_min)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_current_min", "double", 0, "Minimum motor current (regen)", "", &VESCConfig::l_current_min)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_in_current_max = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_in_current_max = 200.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_in_current_max = 60.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_in_current_max", "double", 0, "Maximum battery current", "", &VESCConfig::l_in_current_max)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_in_current_max", "double", 0, "Maximum battery current", "", &VESCConfig::l_in_current_max)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_in_current_min = -200.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_in_current_min = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_in_current_min = -20.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_in_current_min", "double", 0, "Minimum battery current (regen)", "", &VESCConfig::l_in_current_min)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_in_current_min", "double", 0, "Minimum battery current (regen)", "", &VESCConfig::l_in_current_min)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_abs_current_max = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_abs_current_max = 200.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_abs_current_max = 130.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_abs_current_max", "double", 0, "Absolute maximum current", "", &VESCConfig::l_abs_current_max)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_abs_current_max", "double", 0, "Absolute maximum current", "", &VESCConfig::l_abs_current_max)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_min_erpm = -200000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_min_erpm = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_min_erpm = -100000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_min_erpm", "double", 0, "Minimum ERPM", "", &VESCConfig::l_min_erpm)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_min_erpm", "double", 0, "Minimum ERPM", "", &VESCConfig::l_min_erpm)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_max_erpm = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_max_erpm = 200000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_max_erpm = 100000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_max_erpm", "double", 0, "Maximum ERPM", "", &VESCConfig::l_max_erpm)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_max_erpm", "double", 0, "Maximum ERPM", "", &VESCConfig::l_max_erpm)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_max_erpm_fbrake = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_max_erpm_fbrake = 100000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_max_erpm_fbrake = 300.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_max_erpm_fbrake", "double", 0, "Maximum ERPM at full brake", "", &VESCConfig::l_max_erpm_fbrake)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_max_erpm_fbrake", "double", 0, "Maximum ERPM at full brake", "", &VESCConfig::l_max_erpm_fbrake)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_max_erpm_fbrake_cc = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_max_erpm_fbrake_cc = 100000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_max_erpm_fbrake_cc = 1500.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_max_erpm_fbrake_cc", "double", 0, "Maximum ERPM at full brake in current control mode", "", &VESCConfig::l_max_erpm_fbrake_cc)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_max_erpm_fbrake_cc", "double", 0, "Maximum ERPM at full brake in current control mode", "", &VESCConfig::l_max_erpm_fbrake_cc)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_min_vin = 6.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_min_vin = 60.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_min_vin = 8.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_min_vin", "double", 0, "Minimum input voltage", "", &VESCConfig::l_min_vin)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_min_vin", "double", 0, "Minimum input voltage", "", &VESCConfig::l_min_vin)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_max_vin = 6.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_max_vin = 60.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_max_vin = 8.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_max_vin", "double", 0, "Maximum input voltage", "", &VESCConfig::l_max_vin)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_max_vin", "double", 0, "Maximum input voltage", "", &VESCConfig::l_max_vin)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_slow_abs_current = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_slow_abs_current = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_slow_abs_current = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<bool>("l_slow_abs_current", "bool", 0, "Slow absolute maximum current", "", &VESCConfig::l_slow_abs_current)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<bool>("l_slow_abs_current", "bool", 0, "Slow absolute maximum current", "", &VESCConfig::l_slow_abs_current)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_rpm_lim_neg_torque = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_rpm_lim_neg_torque = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_rpm_lim_neg_torque = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<bool>("l_rpm_lim_neg_torque", "bool", 0, "Limit ERPM with negative torque", "", &VESCConfig::l_rpm_lim_neg_torque)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<bool>("l_rpm_lim_neg_torque", "bool", 0, "Limit ERPM with negative torque", "", &VESCConfig::l_rpm_lim_neg_torque)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_temp_fet_start = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_temp_fet_start = 300.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_temp_fet_start = 80.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_temp_fet_start", "double", 0, "MOSFET Temperature Limit Start", "", &VESCConfig::l_temp_fet_start)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_temp_fet_start", "double", 0, "MOSFET Temperature Limit Start", "", &VESCConfig::l_temp_fet_start)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_temp_fet_end = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_temp_fet_end = 300.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_temp_fet_end = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_temp_fet_end", "double", 0, "MOSFET Temperature Limit End", "", &VESCConfig::l_temp_fet_end)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_temp_fet_end", "double", 0, "MOSFET Temperature Limit End", "", &VESCConfig::l_temp_fet_end)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_temp_motor_start = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_temp_motor_start = 300.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_temp_motor_start = 80.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_temp_motor_start", "double", 0, "Motor Temperature Limit Start", "", &VESCConfig::l_temp_motor_start)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_temp_motor_start", "double", 0, "Motor Temperature Limit Start", "", &VESCConfig::l_temp_motor_start)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_temp_motor_end = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_temp_motor_end = 300.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_temp_motor_end = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_temp_motor_end", "double", 0, "Motor Temperature Limit End", "", &VESCConfig::l_temp_motor_end)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_temp_motor_end", "double", 0, "Motor Temperature Limit End", "", &VESCConfig::l_temp_motor_end)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_min_duty = 0.005;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_min_duty = 0.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_min_duty = 0.005;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_min_duty", "double", 0, "Minimum duty cycle", "", &VESCConfig::l_min_duty)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_min_duty", "double", 0, "Minimum duty cycle", "", &VESCConfig::l_min_duty)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_max_duty = 0.01;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_max_duty = 0.95;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_max_duty = 0.95;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_max_duty", "double", 0, "Maximum duty cycle", "", &VESCConfig::l_max_duty)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("l_max_duty", "double", 0, "Maximum duty cycle", "", &VESCConfig::l_max_duty)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sl_min_erpm = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sl_min_erpm = 100000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sl_min_erpm = 150.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_min_erpm", "double", 0, "Sensorless minimum ERPM", "", &VESCConfig::sl_min_erpm)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_min_erpm", "double", 0, "Sensorless minimum ERPM", "", &VESCConfig::sl_min_erpm)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sl_min_erpm_cycle_int_limit = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sl_min_erpm_cycle_int_limit = 10000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sl_min_erpm_cycle_int_limit = 1100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_min_erpm_cycle_int_limit", "double", 0, "Sensorless minimum ERPM for integrator limit", "", &VESCConfig::sl_min_erpm_cycle_int_limit)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_min_erpm_cycle_int_limit", "double", 0, "Sensorless minimum ERPM for integrator limit", "", &VESCConfig::sl_min_erpm_cycle_int_limit)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sl_max_fullbreak_current_dir_change = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sl_max_fullbreak_current_dir_change = 300.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sl_max_fullbreak_current_dir_change = 10.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_max_fullbreak_current_dir_change", "double", 0, "Sensorless maximum full brake current during direction change", "", &VESCConfig::sl_max_fullbreak_current_dir_change)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_max_fullbreak_current_dir_change", "double", 0, "Sensorless maximum full brake current during direction change", "", &VESCConfig::sl_max_fullbreak_current_dir_change)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sl_cycle_int_limit = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sl_cycle_int_limit = 10000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sl_cycle_int_limit = 62.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_cycle_int_limit", "double", 0, "Sensorless integrator limit", "", &VESCConfig::sl_cycle_int_limit)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_cycle_int_limit", "double", 0, "Sensorless integrator limit", "", &VESCConfig::sl_cycle_int_limit)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sl_phase_advance_at_br = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sl_phase_advance_at_br = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sl_phase_advance_at_br = 0.8;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_phase_advance_at_br", "double", 0, "Sensorless phase advance at BR ERPM", "", &VESCConfig::sl_phase_advance_at_br)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_phase_advance_at_br", "double", 0, "Sensorless phase advance at BR ERPM", "", &VESCConfig::sl_phase_advance_at_br)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sl_cycle_int_rpm_br = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sl_cycle_int_rpm_br = 200000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sl_cycle_int_rpm_br = 80000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_cycle_int_rpm_br", "double", 0, "Sensorless BR ERPM", "", &VESCConfig::sl_cycle_int_rpm_br)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_cycle_int_rpm_br", "double", 0, "Sensorless BR ERPM", "", &VESCConfig::sl_cycle_int_rpm_br)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sl_bemf_coupling_k = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sl_bemf_coupling_k = 5000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sl_bemf_coupling_k = 600.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_bemf_coupling_k", "double", 0, "Sensorless BEMF Coupling", "", &VESCConfig::sl_bemf_coupling_k)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("sl_bemf_coupling_k", "double", 0, "Sensorless BEMF Coupling", "", &VESCConfig::sl_bemf_coupling_k)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.hall_table_0 = -1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.hall_table_0 = 6;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.hall_table_0 = -1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_0", "int", 0, "Hall sensor table value 0", "", &VESCConfig::hall_table_0)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_0", "int", 0, "Hall sensor table value 0", "", &VESCConfig::hall_table_0)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.hall_table_1 = -1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.hall_table_1 = 6;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.hall_table_1 = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_1", "int", 0, "Hall sensor table value 1", "", &VESCConfig::hall_table_1)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_1", "int", 0, "Hall sensor table value 1", "", &VESCConfig::hall_table_1)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.hall_table_2 = -1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.hall_table_2 = 6;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.hall_table_2 = 3;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_2", "int", 0, "Hall sensor table value 2", "", &VESCConfig::hall_table_2)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_2", "int", 0, "Hall sensor table value 2", "", &VESCConfig::hall_table_2)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.hall_table_3 = -1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.hall_table_3 = 6;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.hall_table_3 = 2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_3", "int", 0, "Hall sensor table value 3", "", &VESCConfig::hall_table_3)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_3", "int", 0, "Hall sensor table value 3", "", &VESCConfig::hall_table_3)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.hall_table_4 = -1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.hall_table_4 = 6;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.hall_table_4 = 5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_4", "int", 0, "Hall sensor table value 4", "", &VESCConfig::hall_table_4)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_4", "int", 0, "Hall sensor table value 4", "", &VESCConfig::hall_table_4)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.hall_table_5 = -1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.hall_table_5 = 6;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.hall_table_5 = 6;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_5", "int", 0, "Hall sensor table value 5", "", &VESCConfig::hall_table_5)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_5", "int", 0, "Hall sensor table value 5", "", &VESCConfig::hall_table_5)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.hall_table_6 = -1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.hall_table_6 = 6;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.hall_table_6 = 4;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_6", "int", 0, "Hall sensor table value 6", "", &VESCConfig::hall_table_6)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_6", "int", 0, "Hall sensor table value 6", "", &VESCConfig::hall_table_6)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.hall_table_7 = -1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.hall_table_7 = 6;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.hall_table_7 = -1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_7", "int", 0, "Hall sensor table value 7", "", &VESCConfig::hall_table_7)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("hall_table_7", "int", 0, "Hall sensor table value 7", "", &VESCConfig::hall_table_7)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.hall_sl_erpm = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.hall_sl_erpm = 200000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.hall_sl_erpm = 2000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("hall_sl_erpm", "double", 0, "Sensorless ERPM (hybrid mode)", "", &VESCConfig::hall_sl_erpm)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("hall_sl_erpm", "double", 0, "Sensorless ERPM (hybrid mode)", "", &VESCConfig::hall_sl_erpm)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s_pid_kp = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s_pid_kp = 99.99;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s_pid_kp = 0.0001;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("s_pid_kp", "double", 0, "Speed control KP", "", &VESCConfig::s_pid_kp)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("s_pid_kp", "double", 0, "Speed control KP", "", &VESCConfig::s_pid_kp)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s_pid_ki = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s_pid_ki = 99.99;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s_pid_ki = 0.002;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("s_pid_ki", "double", 0, "Speed control KI", "", &VESCConfig::s_pid_ki)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("s_pid_ki", "double", 0, "Speed control KI", "", &VESCConfig::s_pid_ki)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s_pid_kd = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s_pid_kd = 99.99;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s_pid_kd = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("s_pid_kd", "double", 0, "Speed control KD", "", &VESCConfig::s_pid_kd)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("s_pid_kd", "double", 0, "Speed control KD", "", &VESCConfig::s_pid_kd)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s_pid_min_rpm = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s_pid_min_rpm = 200000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s_pid_min_rpm = 900.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("s_pid_min_rpm", "double", 0, "Speed control minimum ERPM", "", &VESCConfig::s_pid_min_rpm)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("s_pid_min_rpm", "double", 0, "Speed control minimum ERPM", "", &VESCConfig::s_pid_min_rpm)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p_pid_kp = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p_pid_kp = 99.99;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p_pid_kp = 0.0001;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("p_pid_kp", "double", 0, "Position control KP", "", &VESCConfig::p_pid_kp)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("p_pid_kp", "double", 0, "Position control KP", "", &VESCConfig::p_pid_kp)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p_pid_ki = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p_pid_ki = 99.99;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p_pid_ki = 0.002;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("p_pid_ki", "double", 0, "Position control KI", "", &VESCConfig::p_pid_ki)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("p_pid_ki", "double", 0, "Position control KI", "", &VESCConfig::p_pid_ki)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p_pid_kd = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p_pid_kd = 99.99;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p_pid_kd = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("p_pid_kd", "double", 0, "Position control KD", "", &VESCConfig::p_pid_kd)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("p_pid_kd", "double", 0, "Position control KD", "", &VESCConfig::p_pid_kd)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cc_startup_boost_duty = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cc_startup_boost_duty = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cc_startup_boost_duty = 0.01;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("cc_startup_boost_duty", "double", 0, "Current control startup boost", "", &VESCConfig::cc_startup_boost_duty)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("cc_startup_boost_duty", "double", 0, "Current control startup boost", "", &VESCConfig::cc_startup_boost_duty)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cc_min_current = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cc_min_current = 99.99;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cc_min_current = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("cc_min_current", "double", 0, "Current control minimum current", "", &VESCConfig::cc_min_current)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("cc_min_current", "double", 0, "Current control minimum current", "", &VESCConfig::cc_min_current)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cc_gain = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cc_gain = 50.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cc_gain = 0.0046;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("cc_gain", "double", 0, "Current control gain", "", &VESCConfig::cc_gain)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("cc_gain", "double", 0, "Current control gain", "", &VESCConfig::cc_gain)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cc_ramp_step_max = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cc_ramp_step_max = 50.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cc_ramp_step_max = 0.04;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("cc_ramp_step_max", "double", 0, "Current control maximum ramp step (at 1000 Hz)", "", &VESCConfig::cc_ramp_step_max)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<double>("cc_ramp_step_max", "double", 0, "Current control maximum ramp step (at 1000 Hz)", "", &VESCConfig::cc_ramp_step_max)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.m_fault_stop_time_ms = -1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.m_fault_stop_time_ms = 40000000;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.m_fault_stop_time_ms = 3000;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("m_fault_stop_time_ms", "int", 0, "Fault stop timeout (in milliseconds)", "", &VESCConfig::m_fault_stop_time_ms)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VESCConfig::AbstractParamDescriptionConstPtr(new VESCConfig::ParamDescription<int>("m_fault_stop_time_ms", "int", 0, "Fault stop timeout (in milliseconds)", "", &VESCConfig::m_fault_stop_time_ms)));
//#line 235 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 235 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(VESCConfig::AbstractGroupDescriptionConstPtr(new VESCConfig::GroupDescription<VESCConfig::DEFAULT, VESCConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<VESCConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<VESCConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<VESCConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    VESCConfig __max__;
    VESCConfig __min__;
    VESCConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const VESCConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static VESCConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &VESCConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const VESCConfig &VESCConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const VESCConfig &VESCConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const VESCConfig &VESCConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<VESCConfig::AbstractParamDescriptionConstPtr> &VESCConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<VESCConfig::AbstractGroupDescriptionConstPtr> &VESCConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const VESCConfigStatics *VESCConfig::__get_statics__()
  {
    const static VESCConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = VESCConfigStatics::get_instance();
    
    return statics;
  }

//#line 8 "/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py"
      const int VESC_Nonsynchronous = 0;
//#line 9 "/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py"
      const int VESC_Synchronous = 1;
//#line 10 "/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py"
      const int VESC_Bipolar = 2;
//#line 13 "/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py"
      const int VESC_Integrate = 0;
//#line 14 "/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py"
      const int VESC_Delay = 1;
//#line 17 "/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py"
      const int VESC_BLDC = 0;
//#line 18 "/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py"
      const int VESC_DC = 1;
//#line 21 "/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py"
      const int VESC_Sensorless = 0;
//#line 22 "/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py"
      const int VESC_Sensored = 1;
//#line 23 "/home/ubuntu/catkin_ws/src/vesc_driver/cfg/VESC.py"
      const int VESC_Hybrid = 2;
}

#endif // __VESCRECONFIGURATOR_H__
